# ---------
# Variables
# ---------
# Make variables
MAKE_DOLLAR := $$

# Project variables
PROJECT_PREFIX = c2c

# --------------------
# Application commands
# --------------------
# Setup frontend for development
setup-dev:
	@echo "\n"
	@echo 'Setup frontend'
	@echo "\n"

# Run frontend in development mode
dev:
	@echo "\n"
	@echo 'Dev frontend'
	@echo "\n"
