# ---------
# Variables
# ---------
# Make variables
MAKE_DOLLAR := $$

# Project variables
PROJECT = change2collect
PROJECT_PREFIX = c2c

# --------------------
# Application commands
# --------------------
# Setup for development
setup-dev:
	@echo "\n"
	@echo Run Frontend Dev Setup
	yarn setup:dev
	@echo "\n"

# Run in development mode
dev:
	@echo "\n"
	@echo Run Frontend Dev
	yarn dev

# Setup for build
setup-build:
	@echo "\n"
	@echo Run Frontend Build Setup
	yarn setup:build
	@echo "\n"

# Generate the build
build:
	@echo "\n"
	@echo Generate Frontend Build
	yarn build
	@echo "\n"

# Run the build
start:
	@echo "\n"
	@echo Start Frontend Build
	yarn start
