# ---------
# Variables
# ---------
# Make variables
MAKE_DOLLAR := $$

# Project variables
PROJECT_PREFIX = c2c

# --------------------
# Application commands
# --------------------
# Setup backend for development
setup-dev:
	@echo "\n"
	@echo 'Setup backend'
	@echo "\n"

# Run backend in development mode
dev:
	@echo "\n"
	@echo 'Dev backend'
	@echo "\n"
